version: "3"
networks:
  gamma:

services:
  gamma-db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    networks:
      - gamma

  gamma-frontend:
    image: cthit/gamma-frontend:development
    network_mode: host
    depends_on:
      - gamma-backend

  gamma-backend:
    image: cthit/gamma-backend:development
    environment:
      # Default admin user name = admin
      # Default admin password  = password

      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: gamma-db
      DB_PORT: 5432
      DB_NAME: postgres

      REDIS_HOST: redis
      REDIS_PASSWORD: ""

      SERVER_PORT: 8081
      FRONTEND_REDIRECT_URI: http://localhost:3000/login
      SUCCESSFUL_LOGIN: http://localhost:3000
      CORS_ALLOWED_ORIGIN: http://localhost:3000
      COOKIE_DOMAIN: localhost
      PRODUCTION: "false"
      IS_MOCKING_CLIENT: "true"
      DEFAULT_REDIRECT_URI: http://localhost:3001/callback
    networks:
      - gamma
    depends_on:
      - gamma-db
      - redis
    volumes:
      - ./mock/mock.json:/mock/mock.json
    ports:
      - 8081:8081

  redis:
    image: redis:5.0
    networks:
      - gamma

  # LDAP ============================

  ldap:
    image: osixia/openldap:1.4.0
    environment:
      #admin username: cn=admin,dc=chalmers,dc=it
      #admin password: password

      LDAP_ORGANISATION: "Chalmers IT"
      LDAP_DOMAIN: "chalmers.it"
      LDAP_BASE_DN: "dc=chalmers,dc=it"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_SEED_INTERNAL_LDIF_PATH: /ldif
      LDAP_SEED_INTERNAL_SCHEMA_PATH: /schemas
    volumes:
      - ./mock/ldif:/ldif
      - ./mock/schemas:/schemas
    ports:
      - 389:389
      - 636:636

  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap
    ports:
      - 8080:80
